title: "discord.py tips"
summary: "discord.pyを利用したdiscordbot開発者向け情報です。"
topics: ["discord", "python", "bot"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
